export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  REQUIRES_2FA: 'REQUIRES_2FA',
  INVALID_2FA: 'INVALID_2FA',
  
  // KYC
  KYC_REQUIRED: 'KYC_REQUIRED',
  KYC_PENDING: 'KYC_PENDING',
  
  // Trading
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  TRADE_LIMIT_EXCEEDED: 'TRADE_LIMIT_EXCEEDED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  TRADE_NOT_FOUND: 'TRADE_NOT_FOUND',
  INVALID_TRADE_STATE: 'INVALID_TRADE_STATE',
  
  // Withdrawal
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',
  MONTHLY_LIMIT_EXCEEDED: 'MONTHLY_LIMIT_EXCEEDED',
  ADDRESS_COOLDOWN: 'ADDRESS_COOLDOWN',
  ADDRESS_NEW: 'ADDRESS_NEW',
  ADDRESS_LIMIT: 'ADDRESS_LIMIT',
  WITHDRAWAL_COOLDOWN: 'WITHDRAWAL_COOLDOWN',
  
  // Rate Limit
  RATE_LIMITED: 'RATE_LIMITED',
  
  // Account
  ACTIVE_TRADES_EXIST: 'ACTIVE_TRADES_EXIST',
  ACTIVE_POSITIONS_EXIST: 'ACTIVE_POSITIONS_EXIST',
  PENDING_WITHDRAWALS_EXIST: 'PENDING_WITHDRAWALS_EXIST',
  
  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];

/**
 * Create a standardized error response object
 */
export function apiError(code: ErrorCodeType, message: string, details?: unknown) {
  return { error: message, code, ...(details ? { details } : {}) };
}
